/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bp2donemprojesi;

import javax.swing.JFrame;

/**
 *
 * @author emirk
 */
public class Frame extends JFrame {
    /**
     * Creates new form Acilis
     */
    Bolum EEM_Bolumu = new Bolum("Elektrik-Elektronik M.");
    Ogretmen o1 = new Ogretmen("Hasan", "Ağaç", "şifre123",EEM_Bolumu);
    Ogretmen o2 = new Ogretmen("Mustafa", "Mert", "şifre321",EEM_Bolumu);
    Ogretmen o3 = new Ogretmen("Ayşe", "Mutlu", "mutlu",EEM_Bolumu);
    Ogretmen o4 = new Ogretmen("Selin", "Bitki", "bitki123",EEM_Bolumu);
    Ogrenci g1 = new Ogrenci("Emir", "Kalafat", "123", EEM_Bolumu);
    Ogrenci g2 = new Ogrenci("Ahmet", "Papatya", "123", EEM_Bolumu);
    Ogrenci g3 = new Ogrenci("Merve", "Şelale", "123", EEM_Bolumu);
    Ogrenci g4 = new Ogrenci("Şeyma", "Şahin", "123", EEM_Bolumu);
    Ders mat1 = new Ders("Matematik-1", 10, o1,EEM_Bolumu);
    Ders fizik1 = new Ders("Fizik-1", 10, o2,EEM_Bolumu);
    Ders fizik2 = new Ders("Fizik-2", 10, o2,EEM_Bolumu);
    Ders bp1 = new Ders("Bilgisayar Programlama", 10, o3,EEM_Bolumu);
    Ders ing = new Ders("İngilizce", 10, o4,EEM_Bolumu);
    Sınav matS1= new Sınav(mat1);
    Sınav fizik1S1= new Sınav(fizik1);
    Sınav fizik2S1= new Sınav(fizik2);
    Sınav bpS1= new Sınav(bp1);
    Sınav ingS1= new Sınav(ing);
    public boolean Giris(Kullanıcı kullanıcı) {
        return kullanıcı.GirisIslemi(jTextFieldSifre.getText(), kullanıcı.tamAd());
    }

    public void sınavTarihi(Sınav sınav) {
        jLabelIslem.setText(EEM_Bolumu.sınavTarihiAyarla(sınav, jComboBoxGun.getSelectedIndex(), jComboBoxSaat.getSelectedIndex(), jComboBoxGun, jComboBoxSaat));
    }
    public Frame() {
        this.initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jComboBoxTarih = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxIsım = new javax.swing.JComboBox<>();
        jComboBoxDers = new javax.swing.JComboBox<>();
        jButtonEkle = new javax.swing.JButton();
        jTextFieldSifre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jComboBoxGun = new javax.swing.JComboBox<>();
        jTextFieldSinavAdi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldSoruSayisi = new javax.swing.JTextField();
        jLabelIslem = new javax.swing.JLabel();
        jComboBoxSaat = new javax.swing.JComboBox<>();
        jButtonGeri = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxIsım1 = new javax.swing.JComboBox<>();
        jTextFieldSifre1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelIslem1 = new javax.swing.JLabel();
        jButtonGeri1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButtonKontrol = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListDersler = new javax.swing.JList<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSonuç = new javax.swing.JTextField();
        sınavKS = new javax.swing.JLabel();
        jButtonOgrenci = new javax.swing.JButton();
        jButtonOgretmen = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setTitle("Ogremten");

        jComboBoxTarih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "14 Haziran 2021", "15 Haziran 2021", "16 Haziran 2021", "17 Haziran 2021", "18 Haziran 2021", "19 Haziran 2021", "20 Haziran 2021" }));
        jComboBoxTarih.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTarihItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tarih:");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Giriş Yapan Öğretmen:");

        jComboBoxIsım.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hasan Ağaç", "Mustafa Mert", "Ayşe Mutlu", "Selin Bitki" }));
        jComboBoxIsım.setEnabled(false);
        jComboBoxIsım.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxIsımItemStateChanged(evt);
            }
        });

        jComboBoxDers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matematik-1", "Fizik-1", "Fizik-2", "Bilgisayar Programlama", "İngilizce" }));
        jComboBoxDers.setFocusable(false);
        jComboBoxDers.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxDersItemStateChanged(evt);
            }
        });

        jButtonEkle.setText("Sınav Ekle");
        jButtonEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEkleActionPerformed(evt);
            }
        });

        jLabel3.setText("Şifrenizi Giriniz: ");

        jComboBoxGun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar" }));
        jComboBoxGun.setEnabled(false);

        jLabel5.setText("Sınavın Adı:");

        jLabel6.setText("Soru Sayısı:");

        jLabelIslem.setText("İşlem Bekleniyor...");

        jComboBoxSaat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belirtilmedi", "9:00 - 11:00", "10:00 - 12:00", "11:00 - 13:00", "12:00 - 14:00", "13:00 - 15:00", "14:00 - 16:00" }));

        jButtonGeri.setText("Geri");
        jButtonGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator2))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButtonGeri)
                                .addGap(25, 25, 25)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxDers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxIsım, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jFrame1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel6)))
                                    .addComponent(jLabel3))
                                .addGap(39, 39, 39)
                                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jFrame1Layout.createSequentialGroup()
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldSoruSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldSifre, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                            .addComponent(jComboBoxSaat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jFrame1Layout.createSequentialGroup()
                                                .addComponent(jComboBoxTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBoxGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabelIslem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jTextFieldSinavAdi))))
                        .addGap(0, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonGeri))
                    .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxDers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxIsım, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSinavAdi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldSoruSayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxGun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldSifre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEkle))
                .addGap(18, 18, 18)
                .addComponent(jLabelIslem)
                .addGap(25, 25, 25))
        );

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Giriş Yapan Öğrenci:");

        jComboBoxIsım1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Emir Kalafat", "Ahmet Papatya", "Merve Şelale", "Şeyme Şahin" }));
        jComboBoxIsım1.setFocusable(false);
        jComboBoxIsım1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxIsım1ItemStateChanged(evt);
            }
        });
        jComboBoxIsım1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxIsım1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Şifrenizi Giriniz: ");

        jLabelIslem1.setText("İşlem Bekleniyor...");

        jButtonGeri1.setText("Geri");
        jButtonGeri1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGeri1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Sınav Var Mı?");

        jButtonKontrol.setText("Kontrol Et");
        jButtonKontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKontrolActionPerformed(evt);
            }
        });

        jListDersler.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Matematik-1", "Fizik-1", "Fizik-2", "Bilgisayar Programlama", "İngilizce" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(jListDersler);

        jLabel9.setText("Kayıtlı olduğunuz dersi seçiniz.");

        jTextFieldSonuç.setEnabled(false);

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addComponent(jTextFieldSifre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonKontrol, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jTextFieldSonuç))
                .addGap(18, 18, 18)
                .addComponent(jLabelIslem1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addComponent(jButtonGeri1)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxIsım1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 401, Short.MAX_VALUE))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                    .addComponent(jComboBoxIsım1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGeri1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSifre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabelIslem1)
                    .addComponent(jButtonKontrol))
                .addGroup(jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jTextFieldSonuç, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame2Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giris");

        sınavKS.setFont(new java.awt.Font("Futura Md BT", 0, 36)); // NOI18N
        sınavKS.setText("Üniversite Sınav Sistemi");

        jButtonOgrenci.setText("Öğrenci Girişi");
        jButtonOgrenci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrenciActionPerformed(evt);
            }
        });

        jButtonOgretmen.setText("Öğretmen Girişi");
        jButtonOgretmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgretmenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonOgretmen, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonOgrenci, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sınavKS))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(sınavKS)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOgrenci)
                    .addComponent(jButtonOgretmen))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOgretmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgretmenActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame1.pack();
        jFrame1.setVisible(true);
        
    }//GEN-LAST:event_jButtonOgretmenActionPerformed

    private void jButtonOgrenciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrenciActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        jFrame2.pack();
        jFrame2.setVisible(true);
        
    }//GEN-LAST:event_jButtonOgrenciActionPerformed

    private void jComboBoxTarihItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTarihItemStateChanged
        // TODO add your handling code here:
        switch (jComboBoxTarih.getSelectedIndex()) {
            case 0:
            jComboBoxGun.setSelectedIndex(0);
            break;
            case 1:
            jComboBoxGun.setSelectedIndex(1);
            break;
            case 2:
            jComboBoxGun.setSelectedIndex(2);
            break;
            case 3:
            jComboBoxGun.setSelectedIndex(3);
            break;
            case 4:
            jComboBoxGun.setSelectedIndex(4);
            break;
            case 5:
            jComboBoxGun.setSelectedIndex(5);
            break;
            case 6:
            jComboBoxGun.setSelectedIndex(6);
            break;
            case 7:
            jComboBoxGun.setSelectedIndex(7);
            break;
        }
    }//GEN-LAST:event_jComboBoxTarihItemStateChanged

    private void jComboBoxIsımItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxIsımItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIsımItemStateChanged

    private void jComboBoxDersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDersItemStateChanged
        // TODO add your handling code here:
        switch (jComboBoxDers.getSelectedIndex()) {
            case 0:
            jComboBoxIsım.setSelectedIndex(0);
            break;
            case 1:
            jComboBoxIsım.setSelectedIndex(1);
            break;
            case 2:
            jComboBoxIsım.setSelectedIndex(1);
            break;
            case 3:
            jComboBoxIsım.setSelectedIndex(2);
            break;
            case 4:
            jComboBoxIsım.setSelectedIndex(3);
        }
    }//GEN-LAST:event_jComboBoxDersItemStateChanged

    private void jButtonEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEkleActionPerformed
        //TODO add your handling code here:
        if (jTextFieldSinavAdi.getText().equals("") || jTextFieldSoruSayisi.getText().equals("") || jTextFieldSifre.getText().equals("")) {
            jLabelIslem.setText("Eksik değer girişi!");
        } else {
            switch (jComboBoxIsım.getSelectedIndex()) {
                case 0:
                if (Giris(o1)) {
                    jLabelIslem.setText("başarılı");
                    matS1.setSınavAdı(jTextFieldSinavAdi.getText());
                    matS1.setSoruSayısı(Integer.parseInt(jTextFieldSoruSayisi.getText()));
                    sınavTarihi(matS1);
                } else {
                    jLabelIslem.setText("Şifre yanlış");
                }
                break;
                case 1:
                if (Giris(o2)) {
                    jLabelIslem.setText("başarılı");
                    if (jComboBoxDers.getSelectedIndex() == 1) {
                        fizik1S1.setSınavAdı(jTextFieldSinavAdi.getText());
                        fizik1S1.setSoruSayısı(Integer.parseInt(jTextFieldSoruSayisi.getText()));
                        sınavTarihi(fizik1S1);
                    } else if (jComboBoxDers.getSelectedIndex() == 2) {
                        fizik2S1.setSınavAdı(jTextFieldSinavAdi.getText());
                        fizik2S1.setSoruSayısı(Integer.parseInt(jTextFieldSoruSayisi.getText()));
                        sınavTarihi(fizik2S1);

                    }

                } else {
                    jLabelIslem.setText("Şifre yanlış");
                }
                break;
                case 2:
                if (Giris(o3)) {
                    jLabelIslem.setText("başarılı");
                    bpS1.setSınavAdı(jTextFieldSinavAdi.getText());
                    bpS1.setSoruSayısı(Integer.parseInt(jTextFieldSoruSayisi.getText()));
                    sınavTarihi(bpS1);
                } else {
                    jLabelIslem.setText("Şifre yanlış");
                }
                break;
                case 3:
                if (Giris(o4)) {
                    jLabelIslem.setText("başarılı");
                    ingS1.setSınavAdı(jTextFieldSinavAdi.getText());
                    ingS1.setSoruSayısı(Integer.parseInt(jTextFieldSoruSayisi.getText()));
                    sınavTarihi(ingS1);
                } else {
                    jLabelIslem.setText("Şifre yanlış");
                }
                break;
            }
        }
    }//GEN-LAST:event_jButtonEkleActionPerformed

    private void jButtonGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeriActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(false);
        
        setVisible(true);
    }//GEN-LAST:event_jButtonGeriActionPerformed

    private void jComboBoxIsım1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxIsım1ItemStateChanged
        // TODO add your handling code here:
        switch (jComboBoxIsım.getSelectedIndex()) {
            case 0:
            jComboBoxIsım.setSelectedIndex(0);
            break;
            case 1:
            jComboBoxIsım.setSelectedIndex(1);
            break;
            case 2:
            jComboBoxIsım.setSelectedIndex(1);
            break;
            case 3:
            jComboBoxIsım.setSelectedIndex(2);
            break;
            case 4:
            jComboBoxIsım.setSelectedIndex(3);
        }
    }//GEN-LAST:event_jComboBoxIsım1ItemStateChanged

    private void jComboBoxIsım1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxIsım1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxIsım1ActionPerformed

    private void jButtonGeri1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGeri1ActionPerformed
        // TODO add your handling code here:
        jFrame2.setVisible(false);
        setVisible(true);
    }//GEN-LAST:event_jButtonGeri1ActionPerformed

    private void jButtonKontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKontrolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonKontrolActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Frame().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEkle;
    public javax.swing.JButton jButtonGeri;
    public javax.swing.JButton jButtonGeri1;
    public javax.swing.JButton jButtonKontrol;
    public javax.swing.JButton jButtonOgrenci;
    public javax.swing.JButton jButtonOgretmen;
    public javax.swing.JComboBox<String> jComboBoxDers;
    public javax.swing.JComboBox<String> jComboBoxGun;
    public javax.swing.JComboBox<String> jComboBoxIsım;
    public javax.swing.JComboBox<String> jComboBoxIsım1;
    public javax.swing.JComboBox<String> jComboBoxSaat;
    public javax.swing.JComboBox<String> jComboBoxTarih;
    public javax.swing.JFrame jFrame1;
    public javax.swing.JFrame jFrame2;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabel9;
    public javax.swing.JLabel jLabelIslem;
    public javax.swing.JLabel jLabelIslem1;
    public javax.swing.JList<String> jListDersler;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JSeparator jSeparator2;
    public javax.swing.JSeparator jSeparator3;
    public javax.swing.JTextField jTextFieldSifre;
    public javax.swing.JTextField jTextFieldSifre1;
    public javax.swing.JTextField jTextFieldSinavAdi;
    public javax.swing.JTextField jTextFieldSonuç;
    public javax.swing.JTextField jTextFieldSoruSayisi;
    public javax.swing.JLabel sınavKS;
    // End of variables declaration//GEN-END:variables
}
